{ lib, config }:
let
  inherit (lib)
    concatStringsSep mapAttrsToList isAttrs isList isString isInt isBool
    hasAttr filterAttrs optional replaceStrings;

  escapeYamlString = s: replaceStrings [ "'" ] [ "''" ] s;

  resources = config.dsc.resources or {};

  # Collect all dependency names referenced across all resources
  allDeps = builtins.concatLists (mapAttrsToList (name: res: res.dependsOn or []) resources);
  uniqueDeps = lib.unique allDeps;
  knownResourceNames = builtins.attrNames resources;
  unknownDeps = builtins.filter (dep: !(builtins.elem dep knownResourceNames)) uniqueDeps;

  # Validate dependencies - abort with helpful message if unknown refs exist
  validatedDeps =
    if unknownDeps == [] then
      true
    else
      builtins.throw ''
        dscnix: dependsOn references unknown resource(s): ${lib.concatStringsSep ", " unknownDeps}
        Known resources: ${lib.concatStringsSep ", " knownResourceNames}
      '';

  # Trigger validation
  _ = validatedDeps;

  yamlScalar = v:
    if v == null then "null"
    else if isBool v then (if v then "true" else "false")
    else if isInt v then toString v
    else if isString v then "'${escapeYamlString v}'"
    else "'${escapeYamlString (toString v)}'";

  emitListItem = item: indent:
    if isAttrs item then
      let
        nonNull = filterAttrs (k: val: val != null) item;
        keys = builtins.attrNames nonNull;
      in
      if keys == [] then
        "${indent}- {}"
      else
        let
          firstKey = builtins.head keys;
          rest = builtins.tail keys;
          firstValue = nonNull.${firstKey};
          firstLine =
            if isList firstValue || isAttrs firstValue then
              "${indent}- ${firstKey}:\n${yamlValue firstValue (indent + "  ")}"
            else
              "${indent}- ${firstKey}: ${yamlScalar firstValue}";
          restLines = map (k:
            let
              v = nonNull.${k};
            in
            if isList v || isAttrs v then
              "${indent}  ${k}:\n${yamlValue v (indent + "    ")}"
            else
              "${indent}  ${k}: ${yamlScalar v}"
          ) rest;
        in
        concatStringsSep "\n" ([ firstLine ] ++ restLines)
    else if isList item then
      if item == [] then
        "${indent}- []"
      else
        "${indent}- ${yamlValue item (indent + "  ")}"
    else
      "${indent}- ${yamlValue item (indent + "  ")}";

  yamlValue = v: indent:
    if isList v then
      if v == [] then "[]"
      else concatStringsSep "\n" (map (item: emitListItem item indent) v)
    else if isAttrs v then
      let
        nonNull = filterAttrs (k: val: val != null) v;
      in
      if nonNull == {} then "{}"
      else concatStringsSep "\n" (mapAttrsToList (k: val: "${indent}${k}: ${yamlValue val (indent + "  ")}") nonNull)
    else
      yamlScalar v;

  emitProperty = k: v: baseIndent:
    if isList v || isAttrs v then
      "${baseIndent}${k}:\n${yamlValue v (baseIndent + "  ")}"
    else
      "${baseIndent}${k}: ${yamlScalar v}";

  emitResource = name: resource:
    let
      props = resource.properties or {};
      deps = resource.dependsOn or [];
      filteredProps = filterAttrs (k: v: v != null) props;
    in
    concatStringsSep "\n" (
      [ "  - name: '${escapeYamlString name}'" ]
      ++ [ "    type: '${escapeYamlString resource.type}'" ]
      ++ (optional (deps != []) "    dependsOn:")
      ++ (map (dep:
        let
          depType = if hasAttr dep resources then resources.${dep}.type else "Unknown";
        in
        "      - \"[resourceId('${escapeYamlString depType}','${escapeYamlString dep}')]\""
      ) deps)
      ++ (optional (filteredProps != {}) "    properties:")
      ++ (mapAttrsToList (k: v: emitProperty k v "      ") filteredProps)
    );

  name = config.dsc.configurationName or "DSCConfiguration";
in
''
# ${name}
# Generated by dscnix — DSC v3 YAML configuration
$schema: 'https://aka.ms/dsc/schemas/v3/bundled/config/document.json'
resources:
${concatStringsSep "\n" (mapAttrsToList emitResource resources)}
''
